name: Test

on:
  - pull_request
  - push

env:
  BUNDLE_WITHOUT: release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
        puppet:
          - "~> 7.0"
          - "~> 6.29"
        exclude:
          - ruby: "3.1"
            puppet: "~> 6.29"
          - ruby: "3.0"
            puppet: "~> 6.29"

    name: "Ruby ${{ matrix.ruby }} - Puppet ${{ matrix.puppet }}"
    env:
      PUPPET_VERSION: ${{ matrix.puppet }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
      - name: Rubocop
        run: bundle exec rake rubocop
  acceptance:
    runs-on: ubuntu-latest
    env:
      BEAKER_setfile: ${{ matrix.beaker }}
    strategy:
      fail-fast: false
      matrix:
        beaker:
          - debian10-64
          - debian11-64
          # - debian12-64 # not supported yet
    name: Acceptance / Image ${{ matrix.beaker }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Run acceptance
        run: bundle exec rake beaker
